### PR TITLE
Add support for Unix based systems

### PR DESCRIPTION
**Pull request by Nullctipus**
Disabling the synthesizer allows the plugin to run on unix

### CODE REVIEW

**Comment by Nullctipus** [comment]
I probably missed some part, but the plugin loads now

**Comment by imaginary-png** [comment]
Oh cool, I assume you've tested it a bit and everything else seems to be working?

**Comment by Nullctipus** [comment]
everything seems to work, I did miss the loading config part

**Comment by Nullctipus** [comment]
if you find or add anymore voice synthesizer code try to reference `_huntManager.DontUseSynthesizer`

**Pull request merged**
